spring:
  config:
    import: optional:file:.env[.properties]
  datasource:
    url: ${DB_DEV_URL}
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${DB_DEV_ROOT_USERNAME}
    password: ${DB_DEV_ROOT_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        show_sql: true
app:
  jwt-secret: ${JWT_DEV_SECRET}
  jwt-expiration-milliseconds: ${JWT_DEV_EXPIRATION_MILLIS}
springdoc:
  swagger-ui:
    operations-sorter: alpha
    tags-sorter: alpha