insert into products (id, description, name, price, status)
values (1,
        'est congue elementum in hac habitasse platea dictumst morbi vestibulum velit id pretium iaculis diam erat fermentum justo nec',
        'Scallops - 20/30', 212.55, 0),
       (2, 'parturient montes nascetur ridiculus mus etiam vel augue vestibulum rutrum rutrum neque aenean auctor',
        'Soup - Campbells Pasta Fagioli', 130.49, 0),
       (3,
        'enim leo rhoncus sed vestibulum sit amet cursus id turpis integer aliquet massa id lobortis convallis tortor risus dapibus augue',
        'Nantucket - Orange Mango Cktl', 267.75, 0),
       (4, 'nec sem duis aliquam convallis nunc proin at turpis a pede posuere nonummy integer non', 'Currants', 161.34,
        0),
       (5, 'donec ut mauris eget massa tempor convallis nulla neque libero', 'Squash - Acorn', 258.36, 0),
       (6, 'sollicitudin ut suscipit a feugiat et eros vestibulum ac est lacinia nisi venenatis tristique',
        'Cod - Salted, Boneless', 47.73, 0),
       (7, 'sit amet turpis elementum ligula vehicula consequat morbi a ipsum integer', 'Veal - Liver', 112.86, 0),
       (8,
        'duis bibendum morbi non quam nec dui luctus rutrum nulla tellus in sagittis dui vel nisl duis ac nibh fusce',
        'Bread - Burger', 59.29, 0),
       (9, 'vel nisl duis ac nibh fusce lacus purus aliquet at feugiat non pretium quis lectus suspendisse potenti',
        'Venison - Denver Leg Boneless', 90.79, 0),
       (10,
        'habitasse platea dictumst maecenas ut massa quis augue luctus tincidunt nulla mollis molestie lorem quisque ut erat',
        'Nestea - Iced Tea', 191.98, 0),
       (11, 'penatibus et magnis dis parturient montes nascetur ridiculus mus etiam vel augue', 'Beef - Top Sirloin',
        277.66, 0),
       (12, 'volutpat dui maecenas tristique est et tempus semper est quam pharetra magna ac consequat metus sapien',
        'Beer - Creemore', 81.22, 0),
       (13, 'luctus ultricies eu nibh quisque id justo sit amet sapien dignissim', 'Compound - Passion Fruit', 1.93, 0),
       (14,
        'morbi vestibulum velit id pretium iaculis diam erat fermentum justo nec condimentum neque sapien placerat ante nulla justo aliquam quis',
        'Soup - Cream Of Broccoli, Dry', 79.88, 0),
       (15,
        'pede libero quis orci nullam molestie nibh in lectus pellentesque at nulla suspendisse potenti cras in purus eu magna',
        'Mini - Vol Au Vents', 222.96, 0),
       (16,
        'pellentesque eget nunc donec quis orci eget orci vehicula condimentum curabitur in libero ut massa volutpat convallis',
        'Apricots Fresh', 293.38, 0),
       (17, 'leo odio porttitor id consequat in consequat ut nulla sed accumsan felis ut at dolor quis odio consequat',
        'Chevere Logs', 295.39, 0),
       (18,
        'hac habitasse platea dictumst etiam faucibus cursus urna ut tellus nulla ut erat id mauris vulputate elementum',
        'Pepper - Paprika, Spanish', 78.81, 0),
       (19, 'nulla facilisi cras non velit nec nisi vulputate nonummy maecenas tincidunt lacus', 'Chicken - Whole',
        297.08, 0),
       (20, 'dapibus augue vel accumsan tellus nisi eu orci mauris lacinia sapien quis libero nullam sit amet',
        'Wine - Riesling Alsace Ac 2001', 139.2, 0),
       (21,
        'vestibulum eget vulputate ut ultrices vel augue vestibulum ante ipsum primis in faucibus orci luctus et ultrices',
        'Yogurt - Banana, 175 Gr', 168.62, 0),
       (22, 'in faucibus orci luctus et ultrices posuere cubilia curae nulla', 'Wanton Wrap', 56.5, 0),
       (23, 'auctor sed tristique in tempus sit amet sem fusce consequat nulla nisl nunc nisl', 'Beans - Kidney White',
        126.48, 0),
       (24,
        'lobortis ligula sit amet eleifend pede libero quis orci nullam molestie nibh in lectus pellentesque at nulla suspendisse',
        'Tart - Pecan Butter Squares', 13.22, 0),
       (25,
        'ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae mauris viverra diam vitae quam suspendisse potenti',
        'Momiji Oroshi Chili Sauce', 153.01, 0),
       (26, 'augue vel accumsan tellus nisi eu orci mauris lacinia sapien quis libero', 'Cod - Black Whole Fillet',
        118.57, 0),
       (27,
        'neque sapien placerat ante nulla justo aliquam quis turpis eget elit sodales scelerisque mauris sit amet eros suspendisse accumsan tortor',
        'Cake - Box Window 10x10x2.5', 64.24, 0),
       (28,
        'arcu sed augue aliquam erat volutpat in congue etiam justo etiam pretium iaculis justo in hac habitasse platea dictumst',
        'Brandy - Bar', 77.39, 0),
       (29, 'ipsum dolor sit amet consectetuer adipiscing elit proin risus praesent lectus', 'Sugar - Cubes', 100.96,
        0),
       (30, 'est donec odio justo sollicitudin ut suscipit a feugiat et eros vestibulum ac est lacinia nisi',
        'Straw - Regular', 53.31, 0);