insert into products (id, description, name, price) values (1, 'lacus purus aliquet at feugiat non pretium quis lectus suspendisse potenti in eleifend quam a odio in hac habitasse platea', 'Sausage - Liver', 117.5),
                                                           (2, 'pharetra magna vestibulum aliquet ultrices erat tortor sollicitudin mi sit amet lobortis sapien', 'Lettuce - Treviso', 78.73),
                                                           (3, 'imperdiet sapien urna pretium nisl ut volutpat sapien arcu sed augue aliquam erat volutpat in congue', 'Cheese - Manchego, Spanish', 174.53),
                                                           (4, 'sed nisl nunc rhoncus dui vel sem sed sagittis nam congue risus semper porta volutpat quam pede lobortis', 'Yucca', 124.92),
                                                           (5, 'nascetur ridiculus mus etiam vel augue vestibulum rutrum rutrum neque aenean auctor', 'Chips - Potato Jalapeno', 141.69),
                                                           (6, 'vehicula consequat morbi a ipsum integer a nibh in quis justo maecenas rhoncus aliquam lacus', 'Table Cloth 90x90 Colour', 184.16),
                                                           (7, 'luctus rutrum nulla tellus in sagittis dui vel nisl duis ac nibh fusce lacus purus aliquet at', 'Beer - Pilsner Urquell', 43.64),
                                                           (8, 'donec dapibus duis at velit eu est congue elementum in hac habitasse platea dictumst morbi', 'Brandy Apricot', 132.52),
                                                           (9, 'elementum in hac habitasse platea dictumst morbi vestibulum velit id pretium iaculis diam erat fermentum justo nec condimentum neque', 'Flour - Semolina', 34.74),
                                                           (10, 'sem mauris laoreet ut rhoncus aliquet pulvinar sed nisl nunc rhoncus dui vel', 'Bag Clear 10 Lb', 22.49),
                                                           (11, 'leo pellentesque ultrices mattis odio donec vitae nisi nam ultrices libero non mattis pulvinar nulla pede ullamcorper augue a', 'Soap - Hand Soap', 154.51),
                                                           (12, 'ultrices vel augue vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae donec pharetra', 'Broom Handle', 154.66),
                                                           (13, 'quam suspendisse potenti nullam porttitor lacus at turpis donec posuere metus vitae ipsum aliquam non mauris morbi non lectus aliquam', 'Sugar - Invert', 18.38),
                                                           (14, 'penatibus et magnis dis parturient montes nascetur ridiculus mus vivamus vestibulum sagittis', 'Oil - Shortening,liqud, Fry', 17.33),
                                                           (15, 'cursus vestibulum proin eu mi nulla ac enim in tempor turpis nec euismod scelerisque', 'Sprouts - Brussel', 31.6),
                                                           (16, 'in porttitor pede justo eu massa donec dapibus duis at velit eu est congue elementum', 'Papayas', 122.2),
                                                           (17, 'scelerisque mauris sit amet eros suspendisse accumsan tortor quis turpis sed', 'Cookie - Dough Variety', 113.79),
                                                           (18, 'nam dui proin leo odio porttitor id consequat in consequat ut nulla sed accumsan felis ut at', 'Bowl 12 Oz - Showcase 92012', 112.11),
                                                           (19, 'eget nunc donec quis orci eget orci vehicula condimentum curabitur in libero ut', 'Ginger - Crystalized', 187.67),
                                                           (20, 'tellus nulla ut erat id mauris vulputate elementum nullam varius nulla facilisi cras non velit nec nisi', 'Wine - Chablis 2003 Champs', 181.57);
